import logging
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query
from fastapi.responses import FileResponse

from backend.app.deps import get_current_user
from backend.app.models import ImageGenRequest, ImageGenResponse
from backend.app.services.image_gen_service import image_gen_service

logger = logging.getLogger("routes.images")
router = APIRouter(prefix="/api/images", tags=["AI Image Generation & Studio"])

@router.post("/generate", response_model=ImageGenResponse)
async def generate_image(
    req: ImageGenRequest,
    current_user: dict = Depends(get_current_user)
):
    """
    Generate an AI image from a text prompt.
    - Style presets: photorealistic, anime, cyberpunk, 3d_render, cinematic, minimalist, oil_painting
    - Aspect ratios: 1:1, 16:9, 9:16, 4:3
    - Associates output image with the authenticated user.
    """
    user_id = current_user["userId"]
    return await image_gen_service.generate_image(user_id, req)

@router.get("/generated", response_model=List[ImageGenResponse])
async def list_generated_images(
    limit: int = Query(50, ge=1, le=100),
    offset: int = Query(0, ge=0),
    current_user: dict = Depends(get_current_user)
):
    """List all AI images generated by the authenticated user."""
    user_id = current_user["userId"]
    return await image_gen_service.list_user_images(user_id, limit=limit, offset=offset)

@router.get("/generated/{image_id}", response_model=ImageGenResponse)
async def get_generated_image(
    image_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Get metadata for a specific generated image."""
    user_id = current_user["userId"]
    return await image_gen_service.get_image(user_id, image_id)

@router.get("/generated/{image_id}/download")
async def download_generated_image(
    image_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Download/view the physical PNG asset for a generated image."""
    user_id = current_user["userId"]
    file_path = await image_gen_service.get_image_file_path(user_id, image_id)
    return FileResponse(
        path=str(file_path),
        media_type="image/png",
        filename=f"nexora_gen_{image_id[:8]}.png"
    )

@router.delete("/generated/{image_id}")
async def delete_generated_image(
    image_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Delete a generated image record and remove its asset from disk."""
    user_id = current_user["userId"]
    deleted = await image_gen_service.delete_image(user_id, image_id)
    return {"message": "Image deleted successfully", "id": image_id, "success": deleted}
